NETCoreFood/Models/CusineType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.Models
{
    public enum CusineType
    {
        None,
        Indian,
        Italian,
        German
    }
}

NETCoreFood/Models/Resturant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.Models
{
    public class Resturant
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Resturant Name")]
        public string Name { get; set; }

        public CusineType CusineType { get; set; }
    }
}

NETCoreFood/ViewModels/HomeIndexViewModel.cs
using NETCoreFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.ViewModels
{
    public class HomeIndexViewModel :IHomeIndexViewModel
    {

        public IEnumerable<Resturant> Resturants { get; set; }

        public string  CurrentMessage { get; set; }
    }
}

NETCoreFood/ViewModels/IHomeIndexViewModel.cs
using NETCoreFood.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.ViewModels
{
    public interface IHomeIndexViewModel
    {

        IEnumerable<Resturant> Resturants { get; set; }

        string CurrentMessage { get; set; }
    }
}

NETCoreFood/ViewModels/ResturantEditViewModel.cs
using NETCoreFood.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.ViewModels
{
    public class ResturantEditViewModel
    {
        [Required]
        [Display(Name = "Resturant Name")]
        public string Name { get; set; }

        public CusineType cusineType { get; set; }
    }
}

NETCoreFood/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NETCoreFood.Models;
using NETCoreFood.Services;
using NETCoreFood.ViewModels;

namespace NETCoreFood.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private IResturantData _resturantData;
        private IGreeter _greeter;
        private readonly IHomeIndexViewModel _homeIndexViewModel;

        public HomeController(IResturantData resturantData,
                                IGreeter greeter,
                                IHomeIndexViewModel   homeIndexViewModel)
        {
            _resturantData = resturantData;
            _greeter = greeter;
            this._homeIndexViewModel = homeIndexViewModel;
        }
        public IActionResult Index()
        {

            // this will return the JSON result based on the request content type 
            //var res = new Resturant
            //{
            //    Id = 1,
            //    Name = "Bhargava"
            //};
            //return new ObjectResult(res);

            //var res = new Resturant
            //{
            //    Id = 1,
            //    Name = "Bhargava"
            //};

            _homeIndexViewModel.Resturants = _resturantData.GetAll();
            _homeIndexViewModel.CurrentMessage = _greeter.GetMessageOfDay();



            return View(_homeIndexViewModel);

        }


        public IActionResult Details(int id)
        {
            var model = _resturantData.GetResturant(id);

            if(model == null)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
           
        }
        [HttpGet]
        [Authorize]
        public  IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(ResturantEditViewModel resturant)
        {
            if (ModelState.IsValid)
            {
                var _resturant = new Resturant()
                {
                    Name = resturant.Name,
                    CusineType = resturant.cusineType
                };

                var resturantResult = _resturantData.AddResturant(_resturant);

                // instead of directly returning the view which might cause issue if the user refresh's page
                // because the URL is still /home/create and will re-save the same data again.
                //Instead, we can send / route the user to a different page using RedirectToAction()
                //return View("Details", resturantResult);

                return RedirectToAction(nameof(Details), new { id = resturantResult.Id });
            }
            else
            {
                return View();
            }
        }

    }
}

NETCoreFood/Pages/Greeter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NETCoreFood.Services;

namespace NETCoreFood.Pages
{
    public class GreeterModel : PageModel
    {
        private IGreeter _greeter;

        public string Message { get; set; }
        public GreeterModel(IGreeter greeter )
        {
            _greeter = greeter;
        }
        public void OnGet(string name)
        {
            Message = $"{name}: ${_greeter.GetMessageOfDay()}";
        }
    }
}

NETCoreFood/Pages/Resturants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NETCoreFood.Services;
using NETCoreFood.Models;
namespace NETCoreFood.Pages.Resturants
{
    public class ResturantsModel : PageModel
    {
        private IResturantData _resturantdata;

        [BindProperty]
        public NETCoreFood.Models.Resturant  resturant { get; set; }

        public ResturantsModel(IResturantData resturantData )
        {
            _resturantdata = resturantData;
        }
        public IActionResult OnGet(int id)
        {
            resturant= _resturantdata.GetResturant(id);
            return Page();
        }

        public IActionResult OnPost()
        {
            if (ModelState.IsValid)
            {
             resturant= _resturantdata.UpdateResturant(resturant);
                return RedirectToAction("Details", "Home", new { id = resturant.Id });
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

NETCoreFood/ViewComponents/GreeterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using NETCoreFood.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NETCoreFood.ViewComponents
{
    public class GreeterViewComponent: Microsoft.AspNetCore.Mvc.ViewComponent
    {
        private IGreeter _greeter;

        public GreeterViewComponent(IGreeter greeter )
        {
            _greeter = greeter;
        }

        public IViewComponentResult Invoke()
        {
            var model = _greeter.GetMessageOfDay();
            return View("Default", model);
        }

    }
}

NETCoreFood/Pages/Greeter.cshtml
@*This is for the routing, the URL should have the value passed. If not passsed,
404 error is thrown.
@Page  is the first keyword used in the Razor pages. This is a must.   
*@ 
@page
@model NETCoreFood.Pages.GreeterModel
@{
    <div>Message using Model @Model.Message </div>
}

@inject IGreeter Greeter

    <h1>  Message of Day is using Inject: @Greeter.GetMessageOfDay()</h1> 

NETCoreFood/Pages/Resturants/Edit.cshtml
@page "{id}"
@model ResturantsModel
@using NETCoreFood.Pages.Resturants


<h1>Edit @Model.resturant.Name </h1>

<form method="post">
    <div>
        <input type="hidden" asp-for="resturant.Id" />
    </div>
    <div>
        <input asp-for="resturant.Name" />
        <span asp-validation-for="resturant.Name"></span>
    </div>

    <div>
        <select asp-for="resturant.CusineType" asp-items="@Html.GetEnumSelectList<CusineType>()"></select>
        <span asp-validation-for="resturant.CusineType"></span>
    </div>

    <input type="submit" name="save" value="Save" />

    </form>

NETCoreFood/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required: false)
    </footer>
</body>

</html>

NETCoreFood/Views/Home/Create.cshtml
@model Resturant


@{ 
    ViewBag.Title ="Create";
}

<h1>Create </h1>

<form  method="post">

    <div>
    <input asp-for="Name" />
    <span asp-validation-for="Name" ></span>
    </div>

    <div>
        <select asp-for="CusineType" asp-items="@Html.GetEnumSelectList<CusineType>()"></select>
        <span asp-validation-for="CusineType"></span>
    </div>

<input type="submit" name="save" value="Save" />

</form>

NETCoreFood/Views/Home/Details.cshtml
@model Resturant

 @{
     ViewBag.Title = "Details Page Title";
 }
<h1>Details</h1>
<h2>@Model.Name</h2>
<h3>@Model.Id</h3>
<h3>@Model.CusineType</h3>
<a asp-action="Index">Back to index..</a>

@section footer{
    @DateTime.Now
}

NETCoreFood/Views/Home/_Summary.cshtml
<div>@Model.Id</div>

<div>@Model.Name</div>

<div>@Model.CusineType</div>
<div>
    <a href="home/Details/@Model.Id">Details...</a>
    <a asp-action="Details" asp-route-id="@Model.Id">More Info..</a>
    <a href="/Resturants/Edit/@Model.Id">Edit HLink</a>
</div>

NETCoreFood/Views/Home/index.cshtml
@model HomeIndexViewModel

@{
    ViewBag.Title = "Home Page Title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div>@Model.CurrentMessage</div>
<table>
    @foreach (var resturant in Model.Resturants)
    {
        <partial name="_Summary" model=" resturant" />
    }


    <div>
        <a asp-action="Create">Create </a>
    </div>



</table>

@section footer{
    @DateTime.Now;
}

NETCoreFood/Views/Shared/Components/Greeter/Default.cshtml
@model string

<div>
@Model
</div>

NETCoreFood/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <footer>
        @RenderSection("footer", required: false)
        @*@await Component.InvokeAsync("Greeter")*@
        <vc:greeter></vc:greeter>
    </footer>
</body>

</html>